security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  login_check
                
            logout:
                path:   /logout
                target: /
 
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
 
    providers:
        default_provider:
            memory:
                users:
                    admin: { password: adminpass, roles: 'ROLE_ADMIN' }
 
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext