sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
        sonata.formatter.block.formatter:

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig #keep this commented unless you are using media bundle.


        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions

    ckeditor:
        templates:
            browser: 'SonataFormatterBundle:Ckeditor:browser.html.twig'
            upload: 'SonataFormatterBundle:Ckeditor:upload.html.twig'

sonata_admin:
    title: Easy Admin
#    templates:
        # default global templates
#        layout:  SonataAdminBundle::layout.html.twig
#    assets:
#        stylesheets:
            # The sandbox includes default pre-optimized version of some css and js
            # So you can either use them, and add your custom assets here
            #   ~ or ~
            # tweak the assetic.yml and the following lines
#            - assetic/sonata_admin_css.css
#            - assetic/sonata_formatter_css.css
#            - assetic/sonata_jqueryui_css.css
#            - bundles/sonatademo/css/demo.css
#        javascripts:
#            - assetic/sonata_admin_js.js
#            - assetic/sonata_jqueryui_js.js
#            - assetic/sonata_formatter_js.js
#            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js
#            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
#    dashboard:
#        blocks:
#            - { position: left, type: sonata.admin.block.admin_list, settings: { groups: [Settings] } }
#            
#        groups:
#            Settings:
#                items: 
#                    - pandora.admin.page
                    
            
ivory_ck_editor:
    default_config: default
    configs:
        default:
            language:  '%locale%'
            toolbar: full
            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: my-context # Optional, to upload in a custom context
                
sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:  # the default context is mandatory
            providers:
#                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 540 , quality: 100}
                special:   { width: 440, height: 200, quality: 100}
        gallery:
            providers:
                - sonata.media.provider.image
            formats:
                big:   { width: 1280 , quality: 100}
        
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
            
    providers:
        image:
            resizer: sonata.media.resizer.square
        file: 
            allowed_mime_types:
              - video/mp4
              - application/pdf
            allowed_extensions:
              - mp4
              - pdf

