login:
    pattern:   /login/
    defaults:  { _controller: PandoraMainBundle:Default:login }
    
login_check:
    pattern:   /login_check/

logout:
    pattern:   /logout
    
pandora_main:
    pattern: /{url}
    defaults: { _controller: PandoraMainBundle:Default:index }
    requirements:
        url: ".+"
    
        
        
